# GitHub Sponsors configuration for crypto-trading-strategies
# Visit https://github.com/sponsors/wenchung to support this project

github: wenchung

# Support tiers:
# - $2/month: Basic supporter - Get a sponsor badge
# - $5/month: Active supporter - Priority issue responses
# - $10/month: Premium supporter - Custom strategy consultation
